---
  - name: Create user m918 for opizero2
    user:
      name: m918
      groups: orangepi, tty, disk, dialout, sudo, audio, video, plugdev, games, users, systemd-journal, input, netdev, ssh, bluetooth
      append: yes
      password: "{{ pass }}"
    become: yes
    when: hostname == 'opizero2' 

  - name: Create user m918
    user:
      name: m918
      groups: m918, adm, cdrom, sudo, dip, plugdev, render, lpadmin, lxd, sambashare
      append: yes
      password: "{{ pass }}"
    when: hostname != 'opizero2'
    become: yes

  - name: Set up sudo for user m918 without password
    copy:
      dest: /etc/sudoers.d/m918
      content: "m918 ALL=(ALL) NOPASSWD: ALL"
      validate: "visudo -cf %s"
    become: yes