---
# Set your SSH public key here. This should be the contents of your public key file (id_rsa.pub).
ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID1nlRrRtEEcSCW2iBdUKaB2+Ki4TWfDD/1WuIw3jzJH m918 homelab"
