  - name: Download install script for Jellyfin
    command: "curl https://repo.jellyfin.org/install-debuntu.sh"

  - name: Check script integrity - sha256sum & diff
    command: "diff <( curl -s https://repo.jellyfin.org/install-debuntu.sh -o install-debuntu.sh; sha256sum install-debuntu.sh ) <( curl -s https://repo.jellyfin.org/install-debuntu.sh.sha256sum )"
    register: script_diff

  - name: Fail if sha256 sum differs
    fail:
      msg: "sha256 sum error - redownload the file"
    when: script_diff != ""

  - name: Check onboard GPU for HW transcoding
    import_tasks: check_gpu.yml

