---
- name: Load variables
  include_vars:
    file: "services.{{ hostname }}.yml"

- name: Create Docker containers
  include_tasks:
    file: create_containers.yml

- name: Deploy non-conteinerized apps
  include_tasks:
    file: {{ item }}.app.yml
  loop: "apps.{{ hostname }}.yml"

- name: Check if Jellyfin uses RKMPP HW acceleration
  command: "docker exec -it jellyfin /usr/lib/jellyfin-ffmpeg/ffmpeg -v debug -init_hw_device rkmpp=rk -init_hw_device opencl=ocl@rk"
  register: ffmpeg_output
  ignore_errors: true

- name: Print output
  debug: "{{ ffmpeg_output.stdout }}"
