---
  - name: Create user m918
    user:
      name: m918
      groups: wheel
      append: yes

  - name: Set up sudo for user m918 without password
    copy:
      dest: /etc/sudoers.d/m918
      content: "m918 ALL=(ALL) NOPASSWD: ALL"
      validate: "visudo -cf %s"