- name: Install OpenSSH server
  package:
    name: openssh-server
    state: present

- name: Start and enable OpenSSH service
  systemd:
    name: sshd
    state: started

- name: Ensure .ssh directory exists and has proper permissions
  file:
    path: "/home/m918/.ssh"
    state: directory
    mode: 0700

- name: Ensure authorized_keys file exists and has proper permissions
  file:
    path: "/home/m918/.ssh/authorized_keys"
    state: touch
    
- name: Append public key to authorized_keys file
  become: yes
  lineinfile:
    path: "/home/m918/.ssh/authorized_keys"
    line: "{{ lookup('file', '~/.ssh/id_rsa_custom.pub') }}"
    state: present

- name: Enable password login for m918
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication yes"

- name: Disable password login for root user
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"

- name: Reload SSH server
  systemd:
    name: sshd
    state: restarted
