- name: Install OpenSSH server
  apt:
    name: openssh-server
    state: present

- name: Start and enable OpenSSH service
  systemd:
    name: sshd
    state: started

- name: Ensure .ssh directory exists and has proper permissions
  file:
    path: "/home/{{ remote_user }}/.ssh"
    state: directory
    mode: 0700

- name: Check if SSH key is present on the local machine
  delegate_to: localhost
  stat:
    path: "/home/m918/.ssh/id_rsa_custom.pub"
  register: ssh_key_stat

- name: Fail if SSH key is not found
  fail:
    msg: "SSH public key (id_rsa_custom.pub) not found on the local machine."
  when: not ssh_key_stat.stat.exists

- name: Append public key to authorized_keys file
  become: yes
  lineinfile:
    path: "/home/orangepi/.ssh/authorized_keys"
    line: "{{ lookup('file', '~/.ssh/id_rsa_custom.pub') }}"
    state: present

- name: Disable password login for m918
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"

- name: Disable password login for root user
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"

- name: Reload SSH server
  systemd:
    name: sshd
    state: restarted
    
