# - name: Create user m918 with permissions
#   hosts: all
#   roles:
#     - create_user

# - name: Install & setup ssh server
#   hosts: all
#   roles:
#     - setup_ssh
#   become: yes

- name: Install Docker on remote machine
  hosts: all
  roles:
    - install_docker
  become: yes