- name: Set permissions & groups
  hosts: all
  roles:
   - ../roles/create_user
  become: yes


- name: Install & setup ssh server
  hosts: all
  roles:
    - ../roles/setup_ssh
  become: yes

- name: Install Docker on remote machine
  hosts: all
  roles:
    - ../roles/install_docker
  become: yes

- name: Deploy services
  hosts: all
  roles:
    - ../roles/deploy_services
